export const HTTP_STATUS_CODE = {
  // 2xx
  OK: 200,
  CREATED: 201,
  ACCEPTED: 202,

  // 4xx
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  REQUEST_TIMEOUT: 408,
  MISSING_REQUIRED_FIELDS: 422,

  // 5xx
  INTERNAL_SERVER_ERROR: 500,
  BAD_GATEWAY: 502,
};

export const HTTP_STATUS_AUTH_FAILED = [HTTP_STATUS_CODE.UNAUTHORIZED, HTTP_STATUS_CODE.FORBIDDEN];

export const HTTP_ERROR_CODE = {
  VALIDATION_ERROR: 'ValidationError',
  APPLICATION_ERROR: 'ApplicationError',
  UNAUTHORIZED: 'Unauthorized',
  FORBIDDEN: 'Forbidden',
  NOT_FOUND: 'NotFound',
  INTERNAL_SERVER_ERROR: 'InternalServerError',
};
